/**
 * Generated by Yeberson Shader Lab
 * Production Export (TSL / WebGPU)
 */

import * as THREE from 'three';
import { MeshPhysicalNodeMaterial } from 'three/webgpu';
import * as TSL from 'three/tsl';

/**
 * Setup function for you to use in your project.
 * It creates the material and configures the post-processing stack.
 */
export function createShaderScene(scene, camera) {
  const textureLoader = new THREE.TextureLoader();

  // --- Scene Setup ---
  // Creating a default sphere to showcase the material
  const geometry = new THREE.SphereGeometry(2, 64, 64);

  // --- Object Material ---
  const material = new MeshPhysicalNodeMaterial({


  });

  material.colorNode = ((uv) => {
    const p = uv.sub(0.5).mul(TSL.float(1.0).div(1));
    const angle = TSL.atan(p.y, p.x);
    let finalCol = TSL.vec3(0);
    {
      const time = TSL.time.mul(1);
      let dist = TSL.length(p);



      const noise = TSL.mx_noise_float(p.mul(10).add(time)).mul(0.2);
      const ring = TSL.smoothstep(0.1, 0, TSL.abs(dist.add(noise.mul(0.1)).sub(TSL.fract(TSL.float(0.5).add(time)))));
      finalCol = finalCol.add(TSL.color('#6366f1').mul(ring));
    }
    {
      const time = TSL.time.mul(1);
      let dist = TSL.length(p);



      const noise = TSL.mx_noise_float(p.mul(10).add(time)).mul(0.2);
      const ring = TSL.smoothstep(0.1, 0, TSL.abs(dist.add(noise.mul(0.1)).sub(TSL.fract(TSL.float(0.7).add(time)))));
      finalCol = finalCol.add(TSL.color('#ffea00').mul(ring));
    }

    return finalCol.mul(TSL.smoothstep(0.5, 0.3, TSL.length(p))).mul(10.0);
  })(TSL.uv());

  const mesh = new THREE.Mesh(geometry, material);
  scene.add(mesh);

  // --- Post Processing Stack ---
  let post = TSL.pass(scene, camera);
  const postProcessing = post;

  return { material, postProcessing };
}
