/**
 * Generated by Yeberson Shader Lab
 * Production Export (TSL / WebGPU)
 */

import * as THREE from 'three';
import { MeshPhysicalNodeMaterial } from 'three/webgpu';
import * as TSL from 'three/tsl';

/**
 * Setup function for you to use in your project.
 * It creates the material and configures the post-processing stack.
 */
export function createShaderScene(scene, camera) {
  const textureLoader = new THREE.TextureLoader();

  // --- Scene Setup ---
  // Creating a default sphere to showcase the material
  const geometry = new THREE.SphereGeometry(2, 64, 64);

  // --- Object Material ---
  const material = new MeshPhysicalNodeMaterial({
    color: '#101010',
    roughness: 1,
    metalness: 1
  });

  // --- Advanced Dispersion (Transmission) ---
  // Note: This requires the 'post' pass defined below to sample the background.
  const uTr = TSL.float(1);
  const uTh = TSL.float(1.87);
  const uIor = TSL.float(1.5);
  const uDisp = TSL.float(0.06);
  const uCaus = TSL.float(0);

  // We will assign the colorNode after the post-processing pass is defined
  material.transmission = 1.0;
  material.thickness = 1.0;
  material.transparent = true;

  const mesh = new THREE.Mesh(geometry, material);
  scene.add(mesh);

  // --- Post Processing Stack ---
  let post = TSL.pass(scene, camera);

  // Deconstructed Transmission Logic (Dispersion & Refraction)
  material.colorNode = TSL.Fn(() => {
    const N = (TSL.transformedNormalView || TSL.normalView).normalize();
    const V = (TSL.positionViewDirection || TSL.viewDirection).normalize();
    const refractionOffset = N.xy.mul(uTh).mul(uIor.sub(1.0)).mul(0.05);
    const uv = TSL.viewportUV;
    const background = TSL.viewportTexture();

    const r = background.sample(uv.add(refractionOffset.add(uDisp.mul(0.02)))).r;
    const g = background.sample(uv.add(refractionOffset)).g;
    const b = background.sample(uv.add(refractionOffset.sub(uDisp.mul(0.02)))).b;

    const refractedColor = TSL.vec3(r, g, b);
    const fresnel = TSL.pow(TSL.float(1.0).sub(N.dot(V).abs()), TSL.float(5.0));
    const reflection = TSL.mix(refractedColor, TSL.vec3(1.0), fresnel.mul(0.5));

    const time = TSL.time.mul(0.5);
    const wave1 = TSL.sin(uv.x.mul(80).add(time)).add(TSL.sin(uv.y.mul(50).sub(time)));
    const wave2 = TSL.sin(uv.x.mul(-60).add(time.mul(1.5))).add(TSL.sin(uv.y.mul(70).add(time)));
    const combinedWaves = wave1.add(wave2).mul(0.5);
    const sharpCaustics = TSL.max(0.0, TSL.float(1.0).sub(combinedWaves.abs())).pow(3.0);
    const causticPattern = sharpCaustics.mul(uCaus).mul(0.5);

    const finalRefraction = reflection.add(TSL.vec3(causticPattern));
    return finalRefraction.mul(uTr);
  })();
  const postProcessing = post;

  return { material, postProcessing };
}
